<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <PlatformTarget>x64</PlatformTarget>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../GameValueEditor.Modules.PlayAgainExpedition.csproj" />
    <ProjectReference Include="../../../../../GameValueEditor/src/GameValueEditor/GameValueEditor.csproj" />
  </ItemGroup>
</Project>
